kind: ImageDigestMirrorSet
apiVersion: config.openshift.io/v1
metadata:
  name: multiarch-tuning-operator-fbc-staging-index
spec:
  imageDigestMirrors:
    - source: registry.redhat.io/multiarch-tuning/multiarch-tuning-operator-bundle
      mirrors:
        - quay.io/redhat-user-workloads/multiarch-tuning-ope-tenant/multiarch-tuning-operator-v1-x/multiarch-tuning-operator-bundle-v1-x
        - quay.io/redhat-user-workloads/multiarch-tuning-ope-tenant/multiarch-tuning-operator/multiarch-tuning-operator-bundle
    - source: registry.redhat.io/multiarch-tuning/multiarch-tuning-rhel9-operator
      mirrors:
        - quay.io/redhat-user-workloads/multiarch-tuning-ope-tenant/multiarch-tuning-operator-v1-x/multiarch-tuning-operator-v1-x
        - quay.io/redhat-user-workloads/multiarch-tuning-ope-tenant/multiarch-tuning-operator/multiarch-tuning-operator
