apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    multiarch.openshift.io/image: registry.ci.openshift.org/origin/multiarch-tuning-operator:v1.x
  labels:
    config.openshift.io/inject-trusted-cabundle: "true"
  name: multiarch-tuning-operator-trusted-ca
