apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: monitoring-role-binding
  namespace: system
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: monitoring-role
subjects:
  - kind: ServiceAccount
    name: prometheus-k8s
    namespace: openshift-monitoring