kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - ../../base/

patches:
  - target:
      group: operators.coreos.com
      version: v1alpha1
      kind: CatalogSource
      name: multiarch-tuning-operator-catalog
    patch: |-
      - op: replace
        path: /spec/image
        value: registry.ci.openshift.org/ocp/multiarch-tuning-operator-catalog:v1.x
  - target:
      group: operators.coreos.com
      version: v1alpha1
      kind: Subscription
      name: openshift-multiarch-tuning-operator
      namespace: openshift-multiarch-tuning-operator
    patch: |-
      - op: replace
        path: /spec/channel
        value: v1.x
